import{a as L,S as b,i as n}from"./assets/vendor-73qhTu8_.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))u(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const c of s.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&u(c)}).observe(document,{childList:!0,subtree:!0});function r(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function u(t){if(t.ep)return;t.ep=!0;const s=r(t);fetch(t.href,s)}})();const v="55707512-2305e15ffb70fd606127599a4",w="https://pixabay.com/api/";async function d(o,e=1){try{return(await L.get(w,{params:{key:v,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:e}})).data}catch(r){return console.error("Error fetching images from Pixabay:",r.message),{hits:[],totalHits:0}}}const f=document.querySelector(".gallery");document.querySelector(".loader");const m=document.querySelector(".load-btn");let q=new b(".gallery a",{captionsData:"alt",captionDelay:250});function p(o){const e=o.map(r=>`
      <li class="gallery-item">
        <a class="item-link" href="${r.largeImageURL}">
          <img class="gallery-image" src="${r.webformatURL}" alt="${r.tags}" />
        </a>
        <div class="img-info-wrapper">
          <p class="img-info">Likes: <span class="info-accent">${r.likes}</span></p>
          <p class="img-info">Views: <span class="info-accent">${r.views}</span></p>
          <p class="img-info">Comments: <span class="info-accent">${r.comments}</span></p>
          <p class="img-info">Downloads: <span class="info-accent">${r.downloads}</span></p>
        </div>
      </li>
    `).join("");f.insertAdjacentHTML("beforeend",e),q.refresh()}function S(){f.innerHTML=""}function y(){document.querySelector(".loader").classList.add("active")}function g(){document.querySelector(".loader").classList.remove("active")}function h(){m.classList.add("is-visible")}function l(){m.classList.remove("is-visible")}const B=document.querySelector(".form"),E=document.querySelector(".load-btn");let i="",a=1;B.addEventListener("submit",async o=>{if(o.preventDefault(),i=o.target.elements["search-text"].value.trim(),!i){n.error({message:"Please enter a search query!"});return}a=1,S(),l(),y();try{const e=await d(i,a);if(e.hits.length===0){n.error({message:"Sorry, there are no images matching your search query. Please try again!"});return}p(e.hits),a*15<e.totalHits&&h()}catch{n.error({message:"Error fetching images"})}finally{g(),o.target.reset()}});E.addEventListener("click",async()=>{a+=1,l(),y();try{const o=await d(i,a);p(o.hits),a*15>=o.totalHits?(l(),n.info({message:"We're sorry, but you've reached the end of search results."})):h();const e=document.querySelector(".gallery-item");if(e){const r=e.getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})}}catch{n.error({message:"Error fetching images"})}finally{g()}});
//# sourceMappingURL=index.js.map
