import{a as L,S as b,i as a}from"./assets/vendor-73qhTu8_.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))u(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&u(l)}).observe(document,{childList:!0,subtree:!0});function r(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function u(t){if(t.ep)return;t.ep=!0;const o=r(t);fetch(t.href,o)}})();const v="55707512-2305e15ffb70fd606127599a4",w="https://pixabay.com/api/";async function d(s,e=1){try{return(await L.get(w,{params:{key:v,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:e}})).data}catch(r){return console.error("Error fetching images from Pixabay:",r.message),{hits:[],totalHits:0}}}const f=document.querySelector(".gallery");document.querySelector(".loader");const m=document.querySelector(".load-btn");let q=new b(".gallery a",{captionsData:"alt",captionDelay:250});function y(s){const e=s.map(r=>`
      <li class="gallery-item">
        <a class="item-link" href="${r.largeImageURL}">
          <img class="gallery-image" src="${r.webformatURL}" alt="${r.tags}" />
        </a>
        <div class="img-info-wrapper">
          <p class="img-info">Likes: <span class="info-accent">${r.likes}</span></p>
          <p class="img-info">Views: <span class="info-accent">${r.views}</span></p>
          <p class="img-info">Comments: <span class="info-accent">${r.comments}</span></p>
          <p class="img-info">Downloads: <span class="info-accent">${r.downloads}</span></p>
        </div>
      </li>
    `).join("");f.insertAdjacentHTML("beforeend",e),q.refresh()}function S(){f.innerHTML=""}function p(){document.querySelector(".loader").classList.add("active")}function g(){document.querySelector(".loader").classList.remove("active")}function h(){m.classList.add("is-visible")}function c(){m.classList.remove("is-visible")}const B=document.querySelector(".form"),E=document.querySelector(".load-btn");let i="",n=1;B.addEventListener("submit",async s=>{if(s.preventDefault(),i=s.target.elements["search-text"].value.trim(),!i){a.error({message:"Please enter a search query!"});return}n=1,S(),c(),p();try{const e=await d(i,n);if(e.hits.length===0){a.error({message:"Sorry, there are no images matching your search query. Please try again!"});return}y(e.hits),n*15>=e.totalHits?(c(),a.info({message:"We're sorry, but you've reached the end of search results."})):h()}catch{a.error({message:"Error fetching images"})}finally{g(),s.target.reset()}});E.addEventListener("click",async()=>{n+=1,c(),p();try{const s=await d(i,n);y(s.hits),n*15>=s.totalHits?(c(),a.info({message:"We're sorry, but you've reached the end of search results."})):h();const e=document.querySelector(".gallery-item");if(e){const r=e.getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})}}catch{a.error({message:"Error fetching images"})}finally{g()}});
//# sourceMappingURL=index.js.map
